substitutions:
  device_name: garage-light
  friendly_name: Garage
  log_level: INFO

packages:
  device_base: !include base/cloudfree-swm1.yaml

# Initial Settings
esphome:
  on_boot:
    priority: 600
    then:
      # Set Mode
      - select.set:
          id: mode_select
          option: "Motion Activated Light"
      # Set Occupancy Timeout (mins)
      - number.set:
          id: occupancy_timeout
          value: 10