substitutions:
  device_name: master-bedroom-light-1 
  friendly_name: Master Bedroom Hero Light
  host_name: master-bedroom-light-1.local

packages:
  device_base: !include common/treatlife-ds02s.yaml