substitutions:
  device_name: master-bedroom-hallway-light-1
  device_name_alt: master_bedroom_hallway_light
  friendly_name: Master Bedroom Hallway Light 
  host_name: master_bedroom_hallway_light.local

packages:
  device_base: !include common/treatlife-ss02.yaml