substitutions:
  device_name: master-bedroom-light-3 
  friendly_name: Master Bedroom Ceiling Light
  host_name: master-bedroom-light-3.local

packages:
  device_base: !include common/treatlife-ds02s.yaml