substitutions:
  device_name: cloudfree_swm1 #change
  log_level: DEBUG

packages:
  board: !include ../common/esp8266ex.yaml
  default_sensors: !include ../common/default_sensors.yaml
  default_controls: !include ../common/default_controls.yaml

api:
  services:
    - service: turn_on_green_led 
      then:
        - switch.turn_on: green_led
    - service: turn_off_green_led 
      then:
        - switch.turn_off: green_led
    - service: turn_on_blue_led 
      then:
        - switch.turn_on: blue_led
    - service: turn_off_blue_led 
      then:
        - switch.turn_off: blue_led

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
    name: $device_name Button
    internal: True
    on_press:
      - switch.toggle: relay

  - platform: gpio
    pin: 
      number: GPIO05
      mode: INPUT
    id: motion_sensor
    publish_initial_state: true
    name: $device_name Motion
    filters:
      - invert:
    icon: "mdi:motion-sensor"
    # https://www.home-assistant.io/integrations/binary_sensor/#device-class
    device_class: "motion"

    on_state:
      - binary_sensor.template.publish:
          id: occupancy_sensor
          state: !lambda 'return id(motion_sensor).state;'

  - platform: template
    name: $device_name Occupancy
    id: occupancy_sensor
    publish_initial_state: true
    filters:
      - delayed_off: 60000ms
   
  - platform: gpio
    pin: 
      number: GPIO14
      mode: INPUT
    id: daylight_sensor
    publish_initial_state: true
    name: $device_name Daylight
    icon: "mdi:white-balance-sunny"
    filters:
      # Helps prevent spamming messages around dusk
      - delayed_on: 50ms
    device_class: "light"

# light:
#   - platform: status_led
#     name: "Status"
#     pin: GPIO13
#     id: blue_led

switch:
  # D1 - Top - 0V
  - platform: gpio
    id: relay
    name: $device_name Light Switch
    pin: GPIO12
    icon: "mdi:lightbulb"
    # https://www.home-assistant.io/integrations/binary_sensor/#device-class
    device_class: "switch"

    # on_turn_on: 
    #   - switch.turn_off: green_led

    # on_turn_off: #purple when off
    #   - switch.turn_on: green_led

  - platform: gpio
    name: $device_name Status LED (Blue)
    pin: 
      number: GPIO13
      mode: OUTPUT_OPEN_DRAIN
    id: blue_led
    inverted: true
    icon: "mdi:led"
    # https://www.home-assistant.io/integrations/binary_sensor/#device-class
    device_class: "switch"
    internal: True

  # D1 - Bottom GPIO16 - 3.3V
  - platform: gpio
    name: $device_name Status LED (Green)
    pin: 
      number: GPIO16
      mode: OUTPUT
    id: green_led
    # https://www.home-assistant.io/integrations/binary_sensor/#device-class
    device_class: "switch"
    internal: True

  - platform: template
    name: $device_name Occupancy LED
    id: occupancy_led_switch
    icon: "mdi:led-off"
    entity_category: config
    optimistic: true

  - platform: template
    name: $device_name Motion LED
    id: motion_led_switch
    icon: "mdi:led-off"
    entity_category: config
    optimistic: true

number:
  - platform: template
    name: $device_name Timeout (Occupancy)
    id: occupancy_timeout
    unit_of_measurement: "m"
    entity_category: config
    optimistic: true
    min_value: 0
    max_value: 30
    step: 5