substitutions:
  device_name: cloudfree_swm1 #change

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m
  name_add_mac_suffix: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  ap:
    ssid: ${device_name}
    password: !secret esphome_ap_password

api:
  password: !secret esphome_api_password
  services:
    - service: turn_on_green_led 
      then:
        - switch.turn_on: green_led
    - service: turn_off_green_led 
      then:
        - switch.turn_off: green_led
    - service: turn_on_blue_led 
      then:
        - switch.turn_on: blue_led
    - service: turn_off_blue_led 
      then:
        - switch.turn_off: blue_led

ota:
  password: !secret esphome_ota_password

captive_portal:

web_server:
  port: 80

time:
  - platform: homeassistant
    # https://esphome.io/components/time
    id: homeassistant_time

# logger:

button:
  - platform: restart
    id: restart_button
    name: $device_name Restart
    entity_category: diagnostic

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
    name: $device_name Button
    internal: True
    on_press:
      - switch.toggle: relay

  - platform: gpio
    pin: 
      number: GPIO05
      mode: INPUT
    id: motion_sensor
    publish_initial_state: true
    name: $device_name Motion
    filters:
      - invert:
      # Helps prevent spamming messages around dusk
      - delayed_on: 50ms
    icon: "mdi:motion-sensor"
    # https://www.home-assistant.io/integrations/binary_sensor/#device-class
    device_class: "motion"

    on_state:
      - binary_sensor.template.publish:
          id: occupancy_sensor
          state: !lambda 'return id(motion_sensor).state;'

  - platform: template
    name: $device_name Occupancy
    id: occupancy_sensor
    publish_initial_state: true
    filters:
      - delayed_off: 60000ms
   
  - platform: gpio
    pin: 
      number: GPIO14
      mode: INPUT_PULLUP
    id: daylight_sensor
    name: $device_name Daylight
    icon: "mdi:lightbulb-question"
    # filters:
      # - invert:
      # Helps prevent spamming messages around dusk
      # - delayed_on: 50ms
    device_class: "light"

# light:
#   - platform: status_led
#     name: "Status"
#     pin: GPIO13
#     id: blue_led

switch:
  # D1 - Top - 0V
  - platform: gpio
    id: relay
    name: $device_name Light Switch
    pin: GPIO12
    icon: "mdi:lightbulb"
    # https://www.home-assistant.io/integrations/binary_sensor/#device-class
    device_class: "switch"

    # on_turn_on: 
    #   - switch.turn_off: green_led

    # on_turn_off: #purple when off
    #   - switch.turn_on: green_led

  - platform: gpio
    name: $device_name Status LED (Blue)
    pin: 
      number: GPIO13
      mode: OUTPUT_OPEN_DRAIN
    id: blue_led
    inverted: true
    icon: "mdi:led"
    # https://www.home-assistant.io/integrations/binary_sensor/#device-class
    device_class: "switch"
    internal: True

  # D1 - Bottom GPIO16 - 3.3V
  - platform: gpio
    name: $device_name Status LED (Green)
    pin: 
      number: GPIO16
      mode: OUTPUT
    id: green_led
    icon: "mdi:led"
    # https://www.home-assistant.io/integrations/binary_sensor/#device-class
    device_class: "switch"
    internal: True

  - platform: template
    name: "Enable Occupancy LED"
    id: occupancy_led_switch
    entity_category: config
    optimistic: true

  - platform: template
    name: "Enable Motion LED"
    id: motion_led_switch
    entity_category: config
    optimistic: true

number:
  - platform: template
    name: "Timeout (Occupancy)"
    id: occupancy_timeout
    unit_of_measurement: "ms"
    entity_category: config
    optimistic: true
    min_value: 1000
    max_value: 600000
    step: 1000

text_sensor:
  - platform: version
    name: $device_name ESPHome Version
    id: esphome_version
    hide_timestamp: True
  - platform: wifi_info
    ip_address:
      id: ip_address
      name: $device_name IP Address
    mac_address:
      name: $device_name Mac
      id: mac_address

sensor:
  - platform: uptime
    name: $device_name Uptime Sensor
  - platform: wifi_signal
    name: $device_name WiFi Signal