substitutions:
  device_name: dryer-outlet
  friendly_name: Dryer Outlet
  log_level: INFO

packages:
  device_base: !include ../base/avatar-awp12l.yaml

# Initial Settings
# esphome:
#   on_boot:
#     priority: -100
#     then:
#       - number.set:
#           id: dimmer_min
#           value: 10
#       - select.set:
#           id: dimmer_mode
#           option: Mode 3