substitutions:
  device_name: kitchen-light-1
  device_name_alt: kitchen_light_1
  friendly_name: Kitchen Light
  host_name: kitchen_light_1.local

packages:
  device_base: !include ../base/treatlife-ss02.yaml