substitutions:
  device_name: acenx_smart_power

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m
  name_add_mac_suffix: true

# Enable logging
logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  ap:
    ssid: ${device_name}
    password: !secret esphome_ap_password

api:
  password: !secret esphome_api_password

ota:
  password: !secret esphome_ota_password

web_server:
  port: 80

captive_portal:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO16
      mode: INPUT_PULLUP
      inverted: yes
    name: "${device_name} Power Button"
    id: "${device_name}_power_button"
    on_press:
      then:
        - switch.toggle: "${device_name}_usb"
        - switch.toggle: "${device_name}_switch1"
        - switch.toggle: "${device_name}_switch2"
        - switch.toggle: "${device_name}_switch3"
switch:
  - platform: gpio
    name: "${device_name} Switch1"
    id: "${device_name}_switch1"
    pin: GPIO14
    restore_mode: "RESTORE_DEFAULT_ON"
  - platform: gpio
    name: "${device_name} Switch2"
    id: "${device_name}_switch2"
    pin: GPIO12
    restore_mode: "RESTORE_DEFAULT_ON"
  - platform: gpio
    name: "${device_name} Switch3"
    id: "${device_name}_switch3"
    pin: GPIO13
    restore_mode: "RESTORE_DEFAULT_ON"
  - platform: gpio
    name: "${device_name} usb"
    id: "${device_name}_usb"
    pin: GPIO05
    restore_mode: "RESTORE_DEFAULT_ON"
    on_turn_on:
      - switch.turn_on: led
    on_turn_off:
      - switch.turn_off: led
  - platform: gpio
    id: led
    pin: GPIO0
    inverted: no