substitutions:
  icon: "mdi:light-switch"

packages:
  wifi: !include wifi.yaml

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m

logger:
  level: DEBUG 
  baud_rate: 0

api:
  password: !secret esphome_api_password

ota:
  password: !secret esphome_ota_password

web_server:
  port: 80

uart:
  rx_pin: GPIO13
  tx_pin: GPIO15
  baud_rate: 9600 

tuya:

sensor:
  - platform: wifi_signal
    name: ${friendly_name} WiFi Signal
    update_interval: 60s

  - platform: uptime
    name: ${friendly_name} Uptime

light:
   - platform: "tuya"
     name: ${friendly_name}
     dimmer_datapoint: 3
     switch_datapoint: 1
     min_value_datapoint: 
     min_value: 10
     max_value: 255
