substitutions:
  icon: "mdi:light-switch"

packages:
  wifi: !include wifi.yaml

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m

logger:
  baud_rate: 0

api:
  password: !secret esphome_api_password

ota:
  password: !secret esphome_ota_password

web_server:
  port: 80

uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 115200

tuya:

time:
  - platform: homeassistant
    # https://esphome.io/components/time
    id: homeassistant_time

# logger:

button:
  - platform: restart
    id: restart_button
    name: $device_name Restart
    entity_category: diagnostic

text_sensor:
  - platform: version
    name: $device_name ESPHome Version
    id: esphome_version
    hide_timestamp: True
  - platform: wifi_info
    ip_address:
      id: ip_address
      name: $device_name IP Address
    mac_address:
      name: $device_name Mac
      id: mac_address

# sensor:
#   - platform: uptime
#     name: $device_name Uptime Sensor
#   - platform: wifi_signal
#     name: $device_name WiFi Signal


# sensor:
#   - platform: wifi_signal
#     name: ${friendly_name} WiFi Signal
#     update_interval: 60s

#   - platform: uptime
#     name: ${friendly_name} Uptime

select:
  - platform: "tuya"
    name: "Dimmer Mode"
    enum_datapoint: 0x6a
    options:
      0: Mode 1 
      1: Mode 2
      2: Mode 3 

number:
  - platform: "tuya"
    name: "Dimmer Range"
    number_datapoint: 0x69
    min_value: 10
    max_value: 100 
    step: 10

light:
  - platform: "tuya"
    name: $friendly_name Light
    dimmer_datapoint: 10
    switch_datapoint: 9
    min_value_datapoint: 105
    min_value: 10
    max_value: 1000

fan:
  - platform: "tuya"
    name: $friendly_name Fan 
    switch_datapoint: 1
    speed_datapoint: 3
    speed_count: 4