# Reference: https://www.esphome-devices.com/devices/Gosund-WP9
substitutions:
  device_name: acenx_smart_power

packages:
  board: !include ../common/esp8266ex.yaml
  default_sensors: !include ../common/default_sensors.yaml
  default_controls: !include ../common/default_controls.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO16
      # mode: INPUT_PULLUP
      inverted: yes
    name: "${device_name} Power Button"
    id: "power_button"
    on_press:
      then:
        - switch.toggle: "usb"
        - switch.toggle: "switch1"
        - switch.toggle: "switch2"
        - switch.toggle: "switch3"
switch:
  - platform: gpio
    name: "${device_name} Switch1"
    id: "switch1"
    pin: GPIO14
    restore_mode: "RESTORE_DEFAULT_ON"

  - platform: gpio
    name: "${device_name} Switch2"
    id: "switch2"
    pin: GPIO12
    restore_mode: "RESTORE_DEFAULT_ON"

  - platform: gpio
    name: "${device_name} Switch3"
    id: "switch3"
    pin: GPIO13
    restore_mode: "RESTORE_DEFAULT_ON"

  - platform: gpio
    name: "${device_name} usb"
    id: "usb"
    pin: GPIO05
    restore_mode: "RESTORE_DEFAULT_ON"
    on_turn_on:
      - switch.turn_on: led
    on_turn_off:
      - switch.turn_off: led

  - platform: gpio
    id: led
    pin: GPIO0
    inverted: no